language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t gosho300/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true gosho300/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-629739409943"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_kay:
    secure: "$AWS_SECRET_KEY"